import { createLogger } from './logger.js'

const log = createLogger('team-orch')

import { existsSync, mkdirSync, readFileSync, watch } from 'fs'
import { resolve } from 'path'
import type { SchedulerPlan } from './classifier.js'
import { AGENT_TYPES } from './config.js'
import { type AgentTask, runParallelGroup } from './executor.js'
import { TEMP_DIR } from './paths.js'
import { writeTeamStatus } from './status.js'
import type { ReviewOutput } from './template.js'
import { parseAgentOutput } from './template.js'

// ── Constants ──────────────────────────────────────────

const _MAX_RETRY_TEAM = 2
const TEAM_FILE_TIMEOUT_MS = 120_000

// ── Team mode orchestrator ─────────────────────────────

export async function runTeamMode(_plan: SchedulerPlan, context: Record<string, unknown>): Promise<string> {
  const taskId = `team-${Date.now()}`
  const sharedDir = resolve(TEMP_DIR, taskId)
  mkdirSync(sharedDir, { recursive: true })

  const planFile = resolve(sharedDir, 'plan.md')

  // Track team mode
  writeTeamStatus({
    active: true,
    mode: 'architect-searcher',
    members: [
      { role: 'architect', status: 'running', model: AGENT_TYPES.plan.model },
      { role: 'searcher', status: 'running', model: AGENT_TYPES.search.model },
    ],
    currentPhase: 'research',
    sharedDir,
  })

  // Phase 1: Architect + Searcher in parallel
  const architectTask: AgentTask = {
    type: 'plan',
    model: AGENT_TYPES.plan.model,
    id: 'team-architect',
    task: `分析现有代码结构并出方案。将方案写入 ${planFile}`,
  }
  const searcherTask: AgentTask = {
    type: 'search',
    model: AGENT_TYPES.search.model,
    id: 'team-searcher',
    task: `搜索相关信息。结果写入 ${resolve(sharedDir, 'context.md')}`,
  }

  const agentMap = new Map<string, AgentTask>([
    ['team-architect', architectTask],
    ['team-searcher', searcherTask],
  ])

  await runParallelGroup(['team-architect', 'team-searcher'], agentMap, {
    ...context,
    shared_dir: sharedDir,
  })

  // Wait for plan.md with fs.watch timeout
  if (!existsSync(planFile)) {
    await new Promise<void>((resolveTimeout, reject) => {
      const watcher = watch(sharedDir, (_eventType, filename) => {
        if (filename === 'plan.md' && existsSync(planFile)) {
          watcher.close()
          resolveTimeout()
        }
      })
      setTimeout(() => {
        watcher.close()
        reject(new Error('Timeout waiting for plan.md'))
      }, TEAM_FILE_TIMEOUT_MS)
    })
  }

  writeTeamStatus({
    active: true,
    mode: 'coder-reviewer',
    members: [
      { role: 'architect', status: 'completed' },
      { role: 'searcher', status: 'completed' },
      { role: 'coder', status: 'waiting' },
      { role: 'reviewer', status: 'waiting' },
    ],
    currentPhase: 'plan-ready',
    sharedDir,
  })

  // Phase 2: Read plan, spawn Coder(s)
  const planContent = readFileSync(planFile, 'utf-8')

  // Parse modules from plan (JSON in markdown code block) or fallback to headings
  const planOutput = parseAgentOutput(planContent)
  let modules: { name: string; files: string[]; independent: boolean }[] = []

  if (
    planOutput &&
    'modules' in planOutput &&
    Array.isArray((planOutput as unknown as Record<string, unknown>).modules)
  ) {
    modules = (planOutput as unknown as { modules: typeof modules }).modules
  }
  if (modules.length === 0) {
    // Fallback: extract modules from markdown headings (## Module Name)
    const headingRegex = /^##\s+(.+)/gm
    const matchResult = planContent.matchAll(headingRegex)
    for (const m of matchResult) {
      modules.push({ name: m[1].trim(), files: [], independent: true })
    }
  }
  if (modules.length === 0) {
    // Last resort: treat the entire plan as a single module
    modules = [{ name: 'default', files: [], independent: true }]
  }

  // Load context.md if generated by searcher
  const contextMdPath = resolve(sharedDir, 'context.md')
  const contextMd = existsSync(contextMdPath) ? readFileSync(contextMdPath, 'utf-8') : ''

  // Update status: Phase 2 — Coding
  writeTeamStatus({
    active: true,
    mode: 'coder-reviewer',
    members: [
      { role: 'architect', status: 'completed' },
      { role: 'searcher', status: 'completed' },
      ...modules.map(() => ({ role: 'coder', status: 'running' as const, model: AGENT_TYPES.coding.model })),
      ...modules.map(() => ({ role: 'reviewer', status: 'waiting' as const })),
    ],
    currentPhase: 'coding',
    sharedDir,
  })

  // Create one Coder task per module and run in parallel
  const coderTasks: AgentTask[] = modules.map((mod, i) => ({
    type: 'coding',
    model: AGENT_TYPES.coding.model,
    id: `team-coder-${i}`,
    task: `实现模块: ${mod.name}。遵循 plan.md 的方案。\n\n模块文件: ${(mod.files || []).join(', ')}\n\n约束: 只实现本模块 ${mod.name} 的内容，不要改其他模块的代码。`,
    files: mod.files.length > 0 ? mod.files : undefined,
  }))

  const coderAgentMap = new Map(coderTasks.map((t) => [t.id, t]))
  await runParallelGroup(
    coderTasks.map((t) => t.id),
    coderAgentMap,
    { ...context, shared_dir: sharedDir, plan_content: planContent, context_md: contextMd },
  )

  // Phase 3: Reviewers — up to 2 rounds of review cycles
  const MAX_REVIEW_ROUNDS = 2
  let allApproved = false

  for (let round = 0; round < MAX_REVIEW_ROUNDS && !allApproved; round++) {
    writeTeamStatus({
      active: true,
      mode: 'coder-reviewer',
      members: [
        { role: 'architect', status: 'completed' },
        { role: 'searcher', status: 'completed' },
        ...modules.map(() => ({ role: 'coder', status: 'completed' as const })),
        ...modules.map(() => ({ role: 'reviewer', status: 'running' as const })),
      ],
      currentPhase: `review-round-${round + 1}`,
      sharedDir,
    })

    // Create one Reviewer task per module
    const reviewerTasks: AgentTask[] = modules.map((mod, i) => ({
      type: 'review',
      model: AGENT_TYPES.review.model,
      id: `team-reviewer-${i}-r${round}`,
      task: `审查模块 "${mod.name}" 的代码实现。\n模块文件: ${mod.files.join(', ')}\n\n根据 plan.md 的方案评估实现质量。返回 approved 或 changes_requested。如果 changes_requested，请列出具体问题。`,
      files: mod.files.length > 0 ? mod.files : undefined,
    }))

    const reviewerAgentMap = new Map(reviewerTasks.map((t) => [t.id, t]))
    const reviewerResults = await runParallelGroup(
      reviewerTasks.map((t) => t.id),
      reviewerAgentMap,
      { ...context, shared_dir: sharedDir, plan_content: planContent },
    )

    // Check if any reviewer requested changes
    const changesDetails: string[] = []
    for (const [, result] of reviewerResults) {
      const output = parseAgentOutput(result?.response || '')
      if (output && 'status' in output && (output as ReviewOutput).status === 'changes_requested') {
        changesDetails.push(JSON.stringify((output as ReviewOutput).findings || []))
      }
    }

    if (changesDetails.length === 0) {
      allApproved = true
      log.info(`Review round ${round + 1}: all approved`)
      break
    }

    // Changes requested — cycle back to Coders (if not the last round)
    if (round < MAX_REVIEW_ROUNDS - 1) {
      log.info(`Review round ${round + 1}: changes requested, cycling back to Coders`)
      const coderRetryTasks: AgentTask[] = modules.map((mod, i) => ({
        type: 'coding',
        model: AGENT_TYPES.coding.model,
        id: `team-coder-${i}-fix-r${round}`,
        task: `根据 review 反馈修复模块 "${mod.name}" 的问题。\n\nReview 反馈:\n${changesDetails.join('\n---\n')}\n\n只修复列出的问题，不要改动其他代码。`,
        files: mod.files.length > 0 ? mod.files : undefined,
      }))

      const coderRetryAgentMap = new Map(coderRetryTasks.map((t) => [t.id, t]))
      await runParallelGroup(
        coderRetryTasks.map((t) => t.id),
        coderRetryAgentMap,
        { ...context, shared_dir: sharedDir, plan_content: planContent, review_feedback: changesDetails },
      )
    }
  }

  // Phase 4: Conflict detection via git diff
  writeTeamStatus({
    active: true,
    mode: 'conflict-detection',
    members: [
      { role: 'architect', status: 'completed' },
      { role: 'searcher', status: 'completed' },
      ...modules.map(() => ({ role: 'coder', status: 'completed' as const })),
      ...modules.map(() => ({ role: 'reviewer', status: 'completed' as const })),
    ],
    currentPhase: 'conflict-detection',
    sharedDir,
  })

  const conflictedFiles: string[] = []
  try {
    const gitDiffProc = Bun.spawnSync(['git', 'diff', '--name-only', '--diff-filter=U'], { timeout: 10_000 })
    const gitDiff = gitDiffProc.stdout.toString()
    const output = gitDiff.trim()
    if (output) {
      conflictedFiles.push(...output.split('\n').filter(Boolean))
    }
  } catch {
    log.warn('Git conflict detection skipped (not a git repo or git unavailable)')
  }

  if (conflictedFiles.length > 0) {
    log.warn(`Conflicts detected in files`, { files: conflictedFiles })
  } else {
    log.info('No merge conflicts detected')
  }

  // Final status
  writeTeamStatus({
    active: false,
    currentPhase: 'complete',
  })

  return `Team mode complete (${taskId})${conflictedFiles.length > 0 ? `. Conflicts in: ${conflictedFiles.join(', ')}` : ''}`
}
